"""add rejection_reason column to competition

Revision ID: 16078e5a2f06
Revises: 88ff6288e046
Create Date: 2025-10-01 23:33:38.751901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16078e5a2f06"
down_revision: Union[str, Sequence[str], None] = "88ff6288e046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "competitions",
        sa.Column("rejection_reason", sa.String(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("competitions", "rejection_reason")
    # ### end Alembic commands ###
