"""make_min_max_age_nullable

Revision ID: 539b54e1b756
Revises: 86cf6fb1f856
Create Date: 2025-10-05 00:40:32.284847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "539b54e1b756"
down_revision: Union[str, Sequence[str], None] = "86cf6fb1f856"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Make columns nullable
    op.alter_column(
        "competitions", "min_age", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "competitions", "max_age", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "competitions", "max_age", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "competitions", "min_age", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
