"""add_national_scale_to_competition

Revision ID: 6ab3b6975ec1
Revises: 6ddae9ef69aa
Create Date: 2025-10-04 22:16:12.351885

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6ab3b6975ec1"
down_revision: Union[str, Sequence[str], None] = "6ddae9ef69aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
