"""add is_approved column to competition

Revision ID: 6ca15ec72318
Revises: fce1ccadb459
Create Date: 2025-10-01 22:55:48.316292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ca15ec72318"
down_revision: Union[str, Sequence[str], None] = "fce1ccadb459"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "competitions",
        sa.Column(
            "is_approved", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("competitions", "is_approved")
    # ### end Alembic commands ###
