"""update_competition_model_constraints

Revision ID: 6ddae9ef69aa
Revises: 93ea0dd8cf53
Create Date: 2025-10-04 22:05:38.509843

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6ddae9ef69aa"
down_revision: Union[str, Sequence[str], None] = "93ea0dd8cf53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
