"""add is_rejected column to competition

Revision ID: 88ff6288e046
Revises: 6ca15ec72318
Create Date: 2025-10-01 23:23:33.339946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88ff6288e046"
down_revision: Union[str, Sequence[str], None] = "6ca15ec72318"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "competitions",
        sa.Column(
            "is_rejected", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("competitions", "is_rejected")
    # ### end Alembic commands ###
