"""finalize competition model

Revision ID: 93ea0dd8cf53
Revises: 16078e5a2f06
Create Date: 2025-10-04 21:57:53.857247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93ea0dd8cf53"
down_revision: Union[str, Sequence[str], None] = "16078e5a2f06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "competitions", sa.Column("overview", sa.String(length=255), nullable=True)
    )
    op.add_column("competitions", sa.Column("min_age", sa.Integer(), nullable=False))
    op.add_column("competitions", sa.Column("max_age", sa.Integer(), nullable=False))
    op.alter_column(
        "competitions",
        "description",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=8000),
        existing_nullable=True,
    )
    op.alter_column(
        "competitions",
        "location",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "competitions",
        "location",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "competitions",
        "description",
        existing_type=sa.String(length=8000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.drop_column("competitions", "max_age")
    op.drop_column("competitions", "min_age")
    op.drop_column("competitions", "overview")
    # ### end Alembic commands ###
