"""add simple Competitions table

Revision ID: fce1ccadb459
Revises: c6a7cd85d92f
Create Date: 2025-10-01 16:30:07.647682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fce1ccadb459"
down_revision: Union[str, Sequence[str], None] = "c6a7cd85d92f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("competition_link", sa.String(length=500), nullable=True),
        sa.Column("registration_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("background_image_url", sa.String(length=500), nullable=True),
        sa.Column("detail_image_urls", sa.String(length=5000), nullable=False),
        sa.Column("location", sa.String(length=100), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("scale", sa.String(length=20), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_competitions_id"), "competitions", ["id"], unique=False)
    op.create_index(
        op.f("ix_competitions_owner_id"), "competitions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_competitions_title"), "competitions", ["title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_competitions_title"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_owner_id"), table_name="competitions")
    op.drop_index(op.f("ix_competitions_id"), table_name="competitions")
    op.drop_table("competitions")
    # ### end Alembic commands ###
